name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create output directory
      run: mkdir -p dist

    - name: Generate Snake GIF
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ github.repository_owner }}
        output: dist/github-contribution-grid-snake.gif

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
